//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runbook {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Runbook.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NullArgumentExceptionFormat {
            get {
                return ResourceManager.GetString("NullArgumentExceptionFormat", resourceCulture);
            }
        }
        
        internal static string ArgumentExceptionFormat {
            get {
                return ResourceManager.GetString("ArgumentExceptionFormat", resourceCulture);
            }
        }
        
        internal static string CreateManifestCommandText {
            get {
                return ResourceManager.GetString("CreateManifestCommandText", resourceCulture);
            }
        }
        
        internal static string CreateManifestDescriptionText {
            get {
                return ResourceManager.GetString("CreateManifestDescriptionText", resourceCulture);
            }
        }
        
        internal static string ShowManifestCommandText {
            get {
                return ResourceManager.GetString("ShowManifestCommandText", resourceCulture);
            }
        }
        
        internal static string ShowManifestDescriptionText {
            get {
                return ResourceManager.GetString("ShowManifestDescriptionText", resourceCulture);
            }
        }
        
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        internal static string DirectoryNotFoundExceptionFormat {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionFormat", resourceCulture);
            }
        }
        
        internal static string ExportRunbookCommandText {
            get {
                return ResourceManager.GetString("ExportRunbookCommandText", resourceCulture);
            }
        }
        
        internal static string ExportRunbookDescriptionText {
            get {
                return ResourceManager.GetString("ExportRunbookDescriptionText", resourceCulture);
            }
        }
    }
}
